import { DetailedTimelinePayload } from "./types";

export const PAYLOAD: DetailedTimelinePayload = {
  version: "1.0.0",
  stages: [
    {
      id: "stage-1",
      name: "The Awakening — Private Revelation",
      period: "Makkah",
      timespan_ce: "610–613",
      description: "Spiritual preparation before public preaching.",
      items: [
        {
          type: "surah",
          revelation_order: 1,
          name_en: "Al-‘Alaq",
          name_ar: "العلق",
          chapter_number: 96,
          verses_range: "1–5 (initial)",
          location: "Cave of Hira, Makkah",
          themes: ["Knowledge", "Creation", "Faith"],
          notes: "First verses revealed; beginning of Prophethood.",
        },
        {
          type: "surah",
          revelation_order: 2,
          name_en: "Al-Qalam",
          name_ar: "القلم",
          chapter_number: 68,
          location: "Makkah",
          themes: ["Character", "Patience", "Consolation"],
          notes: "Defends the Prophet’s integrity against accusations.",
        },
        {
          type: "surah",
          revelation_order: 3,
          name_en: "Al-Muzzammil",
          name_ar: "المزمل",
          chapter_number: 73,
          location: "Makkah",
          themes: ["Night Prayer", "Discipline", "Preparation"],
          notes: "Call to stand at night and prepare for the mission.",
        },
        {
          type: "surah",
          revelation_order: 4,
          name_en: "Al-Muddaththir",
          name_ar: "المدثر",
          chapter_number: 74,
          location: "Makkah",
          themes: ["Warning", "Purification", "Patience"],
          notes: "Public command: “Arise and warn.”",
        },
        {
          type: "surah",
          revelation_order: 5,
          name_en: "Al-Fatihah",
          name_ar: "الفاتحة",
          chapter_number: 1,
          location: "Makkah",
          themes: ["Guidance", "Supplication", "Mercy"],
          notes: "The Opening; core of daily prayer.",
        },
        {
          type: "event",
          name: "First Revelation",
          year_ce: 610,
          location: "Cave of Hira, Jabal al-Nour",
          linked_surahs: [96],
          notes: "Angel Jibril commands “Read/Recite.”",
        },
      ],
    },
    {
      id: "stage-2",
      name: "Early Public Call",
      period: "Makkah",
      timespan_ce: "613–616",
      description: "Beginning of open preaching; emphasis on faith and morals.",
      items: [
        {
          type: "surah",
          revelation_order: 6,
          name_en: "Al-Lahab",
          name_ar: "المسد",
          chapter_number: 111,
          location: "Makkah",
          themes: ["Opposition", "Accountability"],
          notes: "Condemnation of Abu Lahab’s hostility.",
        },
        {
          type: "surah",
          revelation_order: 7,
          name_en: "At-Takwir",
          name_ar: "التكوير",
          chapter_number: 81,
          location: "Makkah",
          themes: ["Judgment Day", "Cosmic Signs"],
          notes: "Vivid scenes of the Last Day.",
        },
        {
          type: "surah",
          revelation_order: 8,
          name_en: "Al-A‘la",
          name_ar: "الأعلى",
          chapter_number: 87,
          location: "Makkah",
          themes: ["Remembrance", "Purification", "Divine Order"],
        },
        {
          type: "surah",
          revelation_order: 9,
          name_en: "Al-Layl",
          name_ar: "الليل",
          chapter_number: 92,
          location: "Makkah",
          themes: ["Generosity vs. Miserliness", "Moral Choice"],
        },
        {
          type: "surah",
          revelation_order: 10,
          name_en: "Ad-Duhaa & Ash-Sharh",
          name_ar: "الضحى • الشرح",
          chapter_number: [93, 94],
          location: "Makkah",
          themes: ["Consolation", "Hope", "Divine Care"],
          notes: "Reassurance during pauses in revelation.",
        },
        {
          type: "event",
          name: "Public Call Begins",
          year_ce: 613,
          location: "Makkah",
          linked_surahs: [74],
          notes: "Open preaching to Quraysh.",
        },
      ],
    },
    {
      id: "stage-3",
      name: "Opposition & Perseverance",
      period: "Makkah",
      timespan_ce: "616–620",
      description: "Persecution intensifies; revelation strengthens resolve.",
      items: [
        {
          type: "surah",
          revelation_order: 11,
          name_en: "Al-An‘am",
          name_ar: "الأنعام",
          chapter_number: 6,
          location: "Makkah",
          themes: ["Monotheism", "Signs of God", "Refutation of Idolatry"],
        },
        {
          type: "surah",
          revelation_order: 12,
          name_en: "Al-Kahf",
          name_ar: "الكهف",
          chapter_number: 18,
          location: "Makkah",
          themes: ["Trials of Faith", "Patience", "Reliance on God"],
        },
        {
          type: "surah",
          revelation_order: 13,
          name_en: "Maryam",
          name_ar: "مريم",
          chapter_number: 19,
          location: "Makkah",
          themes: ["Prophetic Stories", "Mercy", "Resurrection"],
        },
        {
          type: "surah",
          revelation_order: 14,
          name_en: "Ta-Ha",
          name_ar: "طه",
          chapter_number: 20,
          location: "Makkah",
          themes: ["Story of Musa", "Consolation", "Steadfastness"],
        },
        {
          type: "event",
          name: "Social & Economic Boycott",
          year_ce: 616,
          location: "Makkah",
          linked_surahs: [6, 18, 19, 20],
          notes: "Boycott against Banu Hashim and early Muslims.",
        },
      ],
    },
    {
      id: "stage-4",
      name: "Hope and Transition",
      period: "Late Makkah → Pre-Hijrah",
      timespan_ce: "620–622",
      description: "Renewed hope; preparation for migration to Madinah.",
      items: [
        {
          type: "surah",
          revelation_order: 15,
          name_en: "Al-Isra’ (Bani Isra’il)",
          name_ar: "الإسراء",
          chapter_number: 17,
          location: "Makkah",
          themes: ["Night Journey", "Ethics", "Discipline"],
        },
        {
          type: "surah",
          revelation_order: 16,
          name_en: "Ya-Sin",
          name_ar: "يس",
          chapter_number: 36,
          location: "Makkah",
          themes: ["Warning & Mercy", "Centrality of the Qur’an"],
        },
        {
          type: "surah",
          revelation_order: 17,
          name_en: "Az-Zumar",
          name_ar: "الزمر",
          chapter_number: 39,
          location: "Makkah",
          themes: ["Sincerity", "Tawhid", "Resurrection"],
        },
        {
          type: "event",
          name: "Isra’ and Mi‘raj (Night Journey & Ascension)",
          year_ce: 620,
          location: "From Makkah to Jerusalem; then Heavens",
          linked_surahs: [17],
          notes: "Spiritual elevation; prayer established.",
        },
        {
          type: "event",
          name: "Hijrah (Migration to Madinah)",
          year_ce: 622,
          location: "Makkah → Madinah",
          linked_surahs: [],
          notes: "Marks transition to community-building phase.",
        },
      ],
    },
  ],
  metadata: {
    generated_at: "2025-10-29T00:00:00Z",
    notes:
      "Sequence reflects commonly cited early-revelation ordering and themes; precise chronology among some Makkan surahs can vary by source.",
  },
};
