import { TimelinePayload } from "./types";

export const PAYLOAD: TimelinePayload = {
  meccan: { startAH: -13, endAH: 0 },
  medinan: { startAH: 0, endAH: 10 },
  events: [
    {
      id: "evt_first_revelation",
      title: "First Revelation (Iqra')",
      type: "revelation",
      yearAH: -13,
      month: "Ramadan",
      location: "Hira Cave",
      summary: "Beginning of prophethood; Surah al-ʿAlaq (96).",
      links: ["Ibn Hisham"],
    },
    {
      id: "evt_public_call",
      title: "Public Daʿwah",
      type: "milestone",
      yearAH: -10.5,
      location: "Makkah",
      summary: "Open invitation; persecution intensifies.",
    },
    {
      id: "evt_boycott",
      title: "Boycott of Banu Hashim",
      type: "milestone",
      yearAH: -7.5,
      location: "Makkah",
      summary: "Boycott ~3 years.",
    },
    {
      id: "evt_taif",
      title: "Ṭā’if Journey",
      type: "milestone",
      yearAH: -3,
      location: "Ṭā’if",
      summary: "Seeking support; rejection; duʿā’.",
    },
    {
      id: "evt_pledges",
      title: "Pledges of ʿAqabah",
      type: "treaty",
      yearAH: -2,
      location: "Mina",
      summary: "Medinan supporters pledge allegiance.",
    },
    {
      id: "evt_hijrah",
      title: "Hijrah to Madinah",
      type: "migration",
      yearAH: 0,
      location: "Makkah → Madinah",
      summary: "Start of Medinan era.",
    },
    {
      id: "evt_badr",
      title: "Battle of Badr",
      type: "battle",
      yearAH: 2,
      location: "Badr",
      summary: "Decisive victory.",
    },
    {
      id: "evt_uhud",
      title: "Battle of Uḥud",
      type: "battle",
      yearAH: 3,
      location: "Uḥud",
      summary: "Setback & lessons.",
    },
    {
      id: "evt_khandaq",
      title: "Battle of the Trench",
      type: "battle",
      yearAH: 5,
      location: "Madinah",
      summary: "Confederates repelled.",
    },
    {
      id: "evt_hudaybiyyah",
      title: "Treaty of Ḥudaybiyyah",
      type: "treaty",
      yearAH: 6,
      location: "Hudaybiyyah",
      summary: "Strategic truce.",
    },
    {
      id: "evt_fath",
      title: "Conquest of Makkah",
      type: "milestone",
      yearAH: 8,
      location: "Makkah",
      summary: "Peaceful opening.",
    },
    {
      id: "evt_farewell",
      title: "Farewell Pilgrimage",
      type: "milestone",
      yearAH: 10,
      location: "ʿArafah",
      summary: "Final sermon.",
    },
  ],
  revelations: [
    {
      surahId: 96,
      surahName: "Al-ʿAlaq",
      place: "meccan",
      revelationOrder: 1,
      approxYearAH: -13,
      linkedEventIds: ["evt_first_revelation"],
    },
    {
      surahId: 1,
      surahName: "Al-Fātiḥah",
      place: "meccan",
      revelationOrder: 5,
      approxYearAH: -12.5,
    },
    {
      surahId: 74,
      surahName: "Al-Muddaththir",
      place: "meccan",
      revelationOrder: 4,
      approxYearAH: -12.7,
    },
    {
      surahId: 2,
      surahName: "Al-Baqarah",
      place: "medinan",
      revelationOrder: 87,
      approxYearAH: 2,
      linkedEventIds: ["evt_hijrah"],
      asbab: [
        {
          ayahRange: "2:142-150",
          summary: "Qiblah change toward al-Masjid al-Ḥarām.",
          sources: ["al-Wahidi", "al-Suyuti"],
          confidence: "supported",
        },
      ],
    },
    {
      surahId: 3,
      surahName: "Āl ʿImrān",
      place: "medinan",
      revelationOrder: 89,
      approxYearAH: 3,
      linkedEventIds: ["evt_uhud"],
    },
    {
      surahId: 33,
      surahName: "Al-Aḥzāb",
      place: "medinan",
      revelationOrder: 90,
      approxYearAH: 5,
      linkedEventIds: ["evt_khandaq"],
    },
    {
      surahId: 48,
      surahName: "Al-Fatḥ",
      place: "medinan",
      revelationOrder: 111,
      approxYearAH: 6,
      linkedEventIds: ["evt_hudaybiyyah"],
    },
    {
      surahId: 110,
      surahName: "An-Naṣr",
      place: "medinan",
      revelationOrder: 114,
      approxYearAH: 10,
      linkedEventIds: ["evt_farewell", "evt_fath"],
    },
  ],
};
